name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:

  Hello-World:
    runs-on: ubuntu-latest
    steps:
     - run: echo "🎉 This test job for opened issues was automatically triggered by a ${{ github.event_name }} event."
 
  Yo-Repo:
    runs-on: ubuntu-latest
    steps:
     - run: echo "yo repo ${{ github.repository }}"   
     
  Yo-Repo2:
    runs-on: ubuntu-latest
    steps:
     - run: echo "yo repo ${{ github.repository.url }}"   
     
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Backlog
          column: Triage
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
