name: Test Artifacts

on:
  workflow_dispatch:

jobs:
  Test_Upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Run an echo 
      run: |
        echo [{"removedContributors": ["cnk"],"notifiedContributors": ["cnk","angieyan","ykim25","vanyanv"]}] > doggie.json

    - name: define data
      id: define-data
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const script = require('./github-actions/test-runs/test-run1.js')
          const results = script({ g: github, c: context })
          return results

    - name: update data json
      id: update-data-json
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
       # Glob pattern of file which should be added to the commit
        file_pattern: github-actions/test-runs/data.json

        # Optional commit message and author settings
        commit_message: Update Data JSON
 
       
    - uses: actions/upload-artifact@v4
      with:
        name: doggie
        path: doggie.json


    - name: Save data
      id: save-data
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const results = ${{ steps.define-data.result }}
          const script = require('./github-actions/trigger-schedule/list-inactive-members/trim-inactive-members.js')
          script({ g: github, c: context }, results)

  Test_Download:
    needs: Test_Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Download artifact file 
    - name: Download artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        name: doggie

    - name: Extract artifact
      id: extract-artifact
      run: |
        cat doggie.json
        echo "DOG_VALUE=$(cat doggie.json)" >> $GITHUB_ENV
      
      # echo "::set-env name=DOG_VALUE::$(cat doggie.json)"
        
    - name: Echo download2
      uses: actions/github-script@v7
      id: echo-download2
      with:
        github-token: ${{ secrets.TEST_GHAS }}
        script: |
          console.log("made it here!");
          const dog_val2 = process.env.DOG_VALUE;
          console.log(dog_val2);
          const script = require('./.github/workflows/artifact.js');
          const blah = script({g: github, c: context}, dog_val2 );
          return blah;
          
    # const dog_val2 = ${{ env.dog_val }};          
    # console.log(dog_val2);          
    

    # - name: Echo download3
    #   uses: actions/github-script@v6
    #   id: echo-download3
    #   with:
    #     script: console.log( ${{ my-artifact }} )

    
      
