name: Test Artifacts

on:
  workflow_dispatch:

jobs:
  Test_Upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - run: mkdir -p path/to/artifact
    
    - run: echo hello > path/to/artifact/world.txt
    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/world.txt

  Test_Download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Download artifact file 
    - name: Download artifact
      id: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: trim_job_artifact
        path: path/to/artifact/world.txt

    - name: Echo download
      id: echo-download
      run: echo ${{ steps.download-artifact.outputs.result }}
      
