name: Test Artifacts

on:
  workflow_dispatch:

jobs:
  Test_Upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - run: mkdir -p .github/workflows/artifact
    
    - name: Run an echo 
      run: |
        cat > .github/workflows/artifact/world.txt
        yo wassup doggy dog
    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: .github/workflows/artifact/world.txt

  Test_Download:
    needs: Test_Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Download artifact file 
    - name: Download artifact
      id: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: .github/workflows/artifact/world.txt

    - name: display artifact
      run: ls -R

    - name: Echo download path
      run: echo '${{ steps.download-artifact.outputs.download-path }}/world.txt'

    - name: Extract artifact
      id: extract-artifact
      run: |
        cat .github/workflows/artifact/world.txt
      
    # - name: Echo download2
    #   uses: actions/github-script@v6
    #   id: echo-download2
    #   with:
    #     github-token: ${{ secrets.TEST_GHAS }}
    #     script: |
    #       const script = require('/artifact.js');
    #       const blah = script({g: github, c: context});
    #       return blah;

    # - name: Echo download3
    #   uses: actions/github-script@v6
    #   id: echo-download3
    #   with:
    #     script: console.log( ${{ my-artifact }} )

    
      
