name: Test Artifacts

on:
  workflow_dispatch:

jobs:
  Test_Upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - run: mkdir -p path/to/artifact
    
    - run: echo "hello chump" > path/to/artifact/world.txt
    
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: world.txt

  Test_Download:
    needs: Test_Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Download artifact file 
    - name: Download artifact
      id: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        # path: path/to/artifact/world.txt
    - shell: bash
      run: |
        value = `cat world.txt`
        echo $value
          
    - name: Echo download
      id: echo-download
      run: echo ${{ steps.download-artifact.outputs.result }}



    
      
