name: Test Artifacts

on:
  workflow_dispatch:

jobs:
  Test_Upload:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    
    - name: Run an echo 
      run: |
        echo yo wassup doggy dog > doggie.txt
        
    - uses: actions/upload-artifact@v3
      with:
        name: doggie
        path: doggie.txt

  Test_Download:
    needs: Test_Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Download artifact file 
    - name: Download artifact
      id: download-artifact
      uses: actions/download-artifact@v3
      with:
        name: doggie

    - name: display artifact
      run: ls -R

    - name: Extract artifact
      id: extract-artifact
      run: |
        cat doggie.txt
      
    # - name: Echo download2
    #   uses: actions/github-script@v6
    #   id: echo-download2
    #   with:
    #     github-token: ${{ secrets.TEST_GHAS }}
    #     script: |
    #       const script = require('/artifact.js');
    #       const blah = script({g: github, c: context});
    #       return blah;

    # - name: Echo download3
    #   uses: actions/github-script@v6
    #   id: echo-download3
    #   with:
    #     script: console.log( ${{ my-artifact }} )

    
      
